 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/groceries", type: :request do
  
  # Grocery. As you add validations to Grocery, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Grocery.create! valid_attributes
      get groceries_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      grocery = Grocery.create! valid_attributes
      get grocery_url(grocery)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_grocery_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      grocery = Grocery.create! valid_attributes
      get edit_grocery_url(grocery)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Grocery" do
        expect {
          post groceries_url, params: { grocery: valid_attributes }
        }.to change(Grocery, :count).by(1)
      end

      it "redirects to the created grocery" do
        post groceries_url, params: { grocery: valid_attributes }
        expect(response).to redirect_to(grocery_url(Grocery.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Grocery" do
        expect {
          post groceries_url, params: { grocery: invalid_attributes }
        }.to change(Grocery, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post groceries_url, params: { grocery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested grocery" do
        grocery = Grocery.create! valid_attributes
        patch grocery_url(grocery), params: { grocery: new_attributes }
        grocery.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the grocery" do
        grocery = Grocery.create! valid_attributes
        patch grocery_url(grocery), params: { grocery: new_attributes }
        grocery.reload
        expect(response).to redirect_to(grocery_url(grocery))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        grocery = Grocery.create! valid_attributes
        patch grocery_url(grocery), params: { grocery: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested grocery" do
      grocery = Grocery.create! valid_attributes
      expect {
        delete grocery_url(grocery)
      }.to change(Grocery, :count).by(-1)
    end

    it "redirects to the groceries list" do
      grocery = Grocery.create! valid_attributes
      delete grocery_url(grocery)
      expect(response).to redirect_to(groceries_url)
    end
  end
end
